name: Prettier Formatting

on:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0

      - name: Install Dependencies
        run: npm i prettier

      - name: Run Prettier
        run: npx prettier --write .
